version: '3.8'

services:
  app:
    image: laravelsail/php83-composer
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: jagir
      DB_USERNAME: root
      DB_PASSWORD: secret
    command: >
      sh -c "
        composer install &&
        php artisan migrate &&
        php artisan db:seed &&
        php artisan serve --host=0.0.0.0 --port=8000
      "

  db:
    image: mysql:8.0
    container_name: laravel_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: jagir
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
